// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhaleSpotting;

#nullable disable

namespace WhaleSpotting.Migrations
{
    [DbContext(typeof(WhaleSpottingContext))]
    [Migration("20230921115026_AddSpeciesAndBodyOfWaterSeedData")]
    partial class AddSpeciesAndBodyOfWaterSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhaleSpotting.Models.Database.BodyOfWater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BodiesOfWater");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "South Pacific Ocean"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Indian Ocean"
                        },
                        new
                        {
                            Id = -3,
                            Name = "North Pacific Ocean"
                        },
                        new
                        {
                            Id = -4,
                            Name = "South Atlantic Ocean"
                        },
                        new
                        {
                            Id = -5,
                            Name = "Southern Ocean"
                        },
                        new
                        {
                            Id = -6,
                            Name = "North Atlantic Ocean"
                        },
                        new
                        {
                            Id = -7,
                            Name = "Arctic Ocean"
                        },
                        new
                        {
                            Id = -8,
                            Name = "Ross Sea"
                        },
                        new
                        {
                            Id = -9,
                            Name = "Weddell Sea"
                        },
                        new
                        {
                            Id = -10,
                            Name = "Philippine Sea"
                        },
                        new
                        {
                            Id = -11,
                            Name = "Norwegian Sea"
                        },
                        new
                        {
                            Id = -12,
                            Name = "Barents Sea"
                        },
                        new
                        {
                            Id = -13,
                            Name = "Tasman Sea"
                        },
                        new
                        {
                            Id = -14,
                            Name = "Arabian Sea"
                        },
                        new
                        {
                            Id = -15,
                            Name = "Coral Sea"
                        },
                        new
                        {
                            Id = -16,
                            Name = "Bering Sea"
                        },
                        new
                        {
                            Id = -17,
                            Name = "Sargasso Sea"
                        },
                        new
                        {
                            Id = -18,
                            Name = "Greenland Sea"
                        },
                        new
                        {
                            Id = -19,
                            Name = "South China Sea"
                        },
                        new
                        {
                            Id = -20,
                            Name = "Caribbean Sea"
                        },
                        new
                        {
                            Id = -21,
                            Name = "Kara Sea"
                        },
                        new
                        {
                            Id = -22,
                            Name = "Sea of Okhotsk"
                        },
                        new
                        {
                            Id = -23,
                            Name = "Bay of Bengal"
                        },
                        new
                        {
                            Id = -24,
                            Name = "Scotia Sea"
                        },
                        new
                        {
                            Id = -25,
                            Name = "Gulf of Mexico"
                        },
                        new
                        {
                            Id = -26,
                            Name = "Davis Strait"
                        },
                        new
                        {
                            Id = -27,
                            Name = "Mediterranean Sea"
                        },
                        new
                        {
                            Id = -28,
                            Name = "Baffin Bay"
                        },
                        new
                        {
                            Id = -29,
                            Name = "Mozambique Channel"
                        },
                        new
                        {
                            Id = -30,
                            Name = "Beaufort Sea"
                        },
                        new
                        {
                            Id = -31,
                            Name = "Great Australian Bight"
                        },
                        new
                        {
                            Id = -32,
                            Name = "Labrador Sea"
                        },
                        new
                        {
                            Id = -33,
                            Name = "Bellingshausen Sea"
                        },
                        new
                        {
                            Id = -34,
                            Name = "Drake Passage"
                        },
                        new
                        {
                            Id = -35,
                            Name = "Davis Sea"
                        },
                        new
                        {
                            Id = -36,
                            Name = "North Sea"
                        },
                        new
                        {
                            Id = -37,
                            Name = "Gulf of Guinea"
                        },
                        new
                        {
                            Id = -38,
                            Name = "Andaman Sea"
                        },
                        new
                        {
                            Id = -39,
                            Name = "Sea of Japan"
                        },
                        new
                        {
                            Id = -40,
                            Name = "Arafura Sea"
                        },
                        new
                        {
                            Id = -41,
                            Name = "Solomon Sea"
                        },
                        new
                        {
                            Id = -42,
                            Name = "Laccadive Sea"
                        },
                        new
                        {
                            Id = -43,
                            Name = "East China Sea"
                        },
                        new
                        {
                            Id = -44,
                            Name = "Black Sea"
                        },
                        new
                        {
                            Id = -45,
                            Name = "Laptev Sea"
                        },
                        new
                        {
                            Id = -46,
                            Name = "Prydz Bay"
                        },
                        new
                        {
                            Id = -47,
                            Name = "Gulf of Alaska"
                        },
                        new
                        {
                            Id = -48,
                            Name = "Chukchi Sea"
                        },
                        new
                        {
                            Id = -49,
                            Name = "East Siberian Sea"
                        },
                        new
                        {
                            Id = -50,
                            Name = "Lincoln Sea"
                        },
                        new
                        {
                            Id = -51,
                            Name = "Timor Sea"
                        },
                        new
                        {
                            Id = -52,
                            Name = "Celebes Sea"
                        },
                        new
                        {
                            Id = -53,
                            Name = "Red Sea"
                        },
                        new
                        {
                            Id = -54,
                            Name = "Yellow Sea"
                        },
                        new
                        {
                            Id = -55,
                            Name = "Tyrrhenian Sea"
                        },
                        new
                        {
                            Id = -56,
                            Name = "Caspian Sea"
                        },
                        new
                        {
                            Id = -57,
                            Name = "Gulf of Anadyr"
                        },
                        new
                        {
                            Id = -58,
                            Name = "Denmark Strait"
                        },
                        new
                        {
                            Id = -59,
                            Name = "George VI Sound"
                        },
                        new
                        {
                            Id = -60,
                            Name = "Marguerite Bay"
                        },
                        new
                        {
                            Id = -61,
                            Name = "Geographe Bay"
                        },
                        new
                        {
                            Id = -62,
                            Name = "Gulf of Carpentaria"
                        },
                        new
                        {
                            Id = -63,
                            Name = "Makassar Strait"
                        },
                        new
                        {
                            Id = -64,
                            Name = "Gulf of Tomini"
                        },
                        new
                        {
                            Id = -65,
                            Name = "Molucca Sea"
                        },
                        new
                        {
                            Id = -66,
                            Name = "Buli Bay"
                        },
                        new
                        {
                            Id = -67,
                            Name = "Gulf of Thailand"
                        },
                        new
                        {
                            Id = -68,
                            Name = "Gulf of Aden"
                        },
                        new
                        {
                            Id = -69,
                            Name = "Gulf of Oman"
                        },
                        new
                        {
                            Id = -70,
                            Name = "Alboran Sea"
                        },
                        new
                        {
                            Id = -71,
                            Name = "Balearic Sea"
                        },
                        new
                        {
                            Id = -72,
                            Name = "Gulf of Maine"
                        },
                        new
                        {
                            Id = -73,
                            Name = "Adriatic Sea"
                        },
                        new
                        {
                            Id = -74,
                            Name = "Gulf of St. Lawrence"
                        },
                        new
                        {
                            Id = -75,
                            Name = "Bay of Biscay"
                        },
                        new
                        {
                            Id = -76,
                            Name = "English Channel"
                        },
                        new
                        {
                            Id = -77,
                            Name = "Irish Sea"
                        },
                        new
                        {
                            Id = -78,
                            Name = "Gulf of Bothnia"
                        },
                        new
                        {
                            Id = -79,
                            Name = "Shelikhova Gulf"
                        },
                        new
                        {
                            Id = -80,
                            Name = "Gulf of Yana"
                        },
                        new
                        {
                            Id = -81,
                            Name = "Kane Basin"
                        });
                });

            modelBuilder.Entity("WhaleSpotting.Models.Database.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInHours")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("WhaleSpotting.Models.Database.Interaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("WhaleSpotting.Models.Database.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyOfWaterId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BodyOfWaterId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("WhaleSpotting.Models.Database.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Sperm whale"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Blue whale"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Bowhead whale"
                        },
                        new
                        {
                            Id = -4,
                            Name = "Bryde's whale"
                        },
                        new
                        {
                            Id = -5,
                            Name = "False killer whale"
                        },
                        new
                        {
                            Id = -6,
                            Name = "Fin whale"
                        },
                        new
                        {
                            Id = -7,
                            Name = "Gray whale"
                        },
                        new
                        {
                            Id = -8,
                            Name = "Humpback whale"
                        },
                        new
                        {
                            Id = -9,
                            Name = "Killer whale"
                        },
                        new
                        {
                            Id = -10,
                            Name = "Minke whale"
                        },
                        new
                        {
                            Id = -11,
                            Name = "Pilot whale"
                        },
                        new
                        {
                            Id = -12,
                            Name = "Right whale"
                        },
                        new
                        {
                            Id = -13,
                            Name = "Sei whale"
                        });
                });

            modelBuilder.Entity("WhaleSpotting.Models.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WhaleSpotting.Models.Database.Interaction", b =>
                {
                    b.HasOne("WhaleSpotting.Models.Database.Post", "Post")
                        .WithMany("Interactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhaleSpotting.Models.Database.User", "User")
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhaleSpotting.Models.Database.Post", b =>
                {
                    b.HasOne("WhaleSpotting.Models.Database.BodyOfWater", "BodyOfWater")
                        .WithMany("Posts")
                        .HasForeignKey("BodyOfWaterId");

                    b.HasOne("WhaleSpotting.Models.Database.Species", "Species")
                        .WithMany("Posts")
                        .HasForeignKey("SpeciesId");

                    b.HasOne("WhaleSpotting.Models.Database.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyOfWater");

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhaleSpotting.Models.Database.BodyOfWater", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("WhaleSpotting.Models.Database.Post", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("WhaleSpotting.Models.Database.Species", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("WhaleSpotting.Models.Database.User", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
